"""add price to orders

Revision ID: 7e75790903d1
Revises: b0e83e50c4ea
Create Date: 2026-09-24 08:29:14.362125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e75790903d1'
down_revision: Union[str, Sequence[str], None] = 'b0e83e50c4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=False))
    op.drop_column('orders', 'total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total', sa.FLOAT(), nullable=False))
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
